### ISSUE TITLE
frontier-evm-starter error on Shibuya

### ISSUE THREAD

**Issue by torikare** [subquery/subql#1032]
about https://github.com/subquery/tutorials-frontier-evm-starter.
I changed only the chainId and endpoint in project.yaml to Shibuya's and when I run it, I got an error.
I didn't changed anything except project.yaml.
The project.yaml is as follows
```
specVersion: 1.0.0
name: frontier-evm-starter-project
version: 1.0.0
runner:
  node:
    name: '@subql/node'
    version: '>=0.35.0'
  query:
    name: '@subql/query'
    version: '>=0.16.0'
description: >-
  A basic Frontier EVM example project with an event and call handler. Read more
  about this at https://doc.subquery.network/create/frontier/
repository: https://github.com/subquery/tutorials-frontier-evm-starter
schema:
  file: ./schema.graphql
network:
  chainId: '0xddb89973361a170839f80f152d2e9e38a376a5a7eccefcade763f46a8e567019'
  endpoint: wss://rpc.shibuya.astar.network
  # dictionary: https://api.subquery.network/sq/subquery/moonriver-dictionary
  chaintypes:
    file: ./dist/chaintypes.js
dataSources:
  - kind: substrate/FrontierEvm
    startBlock: 1
    processor:
      file: ./node_modules/@subql/contract-processors/dist/frontierEvm.js
      options:
        abi: erc20
        # address: '0x6bd193ee6d2104f14f94e2ca6efefae561a4334b'
    assets:
      erc20:
        file: ./erc20.abi.json
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleFrontierEvmEvent
          kind: substrate/FrontierEvmEvent
          filter:
            topics:
              - Transfer(address indexed from,address indexed to,uint256 value)
              - null
              - null
              - null
        - handler: handleFrontierEvmCall
          kind: substrate/FrontierEvmCall
          filter:
            function: approve(address to,uint256 value)
            # from: '0x6bd193ee6d2104f14f94e2ca6efefae561a4334b'
```

The error log is as follows
```
subquery-node_1   | 2022-05-15T12:25:25.778Z <fetch> ERROR failed to fetch Block 0xd4a2cf7f6ab1c1d73cd34ad2f0447de02b76e60a6ef308178a97a7496819bd47 
subquery-node_1   | 2022-05-15T12:25:25.778Z <indexer> ERROR failed to fetch block Error: createType(SignedBlock):: Struct: failed on block: {"header":"Header","extrinsics":"Vec<Extrinsic>"}:: Struct: failed on extrinsics: Vec<Extrinsic>:: createType(ExtrinsicV4):: createType(Call):: Call: failed decoding session.setKeys:: Struct: failed on args: {"keys":"Keys","proof":"Bytes"}:: decodeU8a: failed at 0x5469566abaefe40a321f5e153caf417c… on keys: (AccountId,AccountId,AccountId,AccountId):: decodeU8a: failed at 0x0430…: AccountId:: Invalid AccountId provided, expected 32 bytes, found 2
```
