### ISSUE TITLE
Algorand error when `assetId: 0`

### ISSUE THREAD

**Issue by jamesbayly** [subquery/subql#1305]
When i use an `assetId: 0` (Algo token), the indexer will never find anything.

Example project: https://github.com/spapasoteriou/algorand-subquery-randgallery

<img width="885" alt="image" src="https://user-images.githubusercontent.com/46693720/191128121-957df259-ce78-4449-bac1-f8ab26810b83.png">

```
dataSources:
  - kind: algorand/Runtime
    startBlock: 23557938 # Block that Rand account received first transaction. This is used to speed up indexing.
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleTransaction
          kind: algorand/TransactionHandler
          filter:
            # payments to the RandGallery Address for the Algo asset
            txType: pay
            assetId: 0 # Algo token
            receiver: "RANDGVRRYGVKI3WSDG6OGTZQ7MHDLIN5RYKJBABL46K5RQVHUFV3NY5DUE"
```

I also note the the dictionary is always timing out here, potentially it's an issue with the way we parse the GraphQL request?
