### ISSUE TITLE
[Ethereum] Allow specifying headers for network endpoint

### ISSUE THREAD

**Issue by stwiname** [subquery/subql#1420]
For authentication some api services require setting headers, we should allow specifying headers in the project manifest

Example:
```yaml
network:
  endpoint: https://flare-api.flare.network/ext/C/rpc
  headers:
    x-apiKey: "xxxxxxx"
  chainId: "14"

```
