### ISSUE TITLE
[Ethereum] Adding `functions` filter to log handler doesn't throw

### ISSUE THREAD

**Issue by stwiname** [subquery/subql#1478]
Project manifest validation should catch this being an invalid filter:

Example bad handler:
```
    mapping:
      file: "./dist/index.js"
      handlers:
        - handler: handlePoolCreated
          kind: ethereum/LogHandler
          filter:
            function: PoolCreated(indexed address,indexed address,indexed uint24,int24,address)
```

The correct version is:
```
    mapping:
      file: "./dist/index.js"
      handlers:
        - handler: handlePoolCreated
          kind: ethereum/LogHandler
          filter:
            topics:
               - PoolCreated(indexed address,indexed address,indexed uint24,int24,address)
```
