### ISSUE TITLE
subql-ethereum ds handlers, missing address

### ISSUE THREAD

**Issue by bz888** [subquery/subql#1479]
### Prerequisites

* [x] Are you running the latest version(s)?
* [x] Did you check the [debugging guide](https://doc.subquery.network/academy/tutorials_examples/debug-projects.html#how-to-debug-a-subquery-project)?
* [x] Did you check the [FAQs](https://doc.subquery.network/faqs/faqs.html) and [Discussions](https://github.com/subquery/subql/discussions)?
* [x] Are you reporting to the correct repository?
* [x] Did you search for an existing issue or pull request?

### Description
Current 
```
dataSources:
  - kind: ethereum/Runtime
    startBlock: 12369621
    options:
      # Must be a key of assets
      abi: Factory
 
    assets:
      Factory:
        file: "./abis/Factory.json"
    mapping:
      file: "./dist/index.js"
      handlers:
        - handler: handlePoolCreated
          kind: ethereum/LogHandler
          filter:
            topics:
                address: "0x1F98431c8aD98523631AE4a59f267346ea31F984"
              - PoolCreated(indexed address,indexed address,indexed uint24,int24,address)

```

Expect 
```
dataSources:
  - kind: ethereum/Runtime
    startBlock: 12369621
    options:
      # Must be a key of assets
      abi: Factory
      address: "0x1F98431c8aD98523631AE4a59f267346ea31F984"
    assets:
      Factory:
        file: "./abis/Factory.json"
    mapping:
      file: "./dist/index.js"
      handlers:
        - handler: handlePoolCreated
          kind: ethereum/LogHandler
          filter:
            topics:
              - PoolCreated(indexed address,indexed address,indexed uint24,int24,address)

```

`eventFilterToQueryEntry` it should read address from `options.address` and that should be applicable for all handlers in the ds
Current
### Details

These details can help to reproduce the environment the issue is occurring

**Local Environment:** [You can get this information from executing `subql version`.]
**Query Version:** [What is the version of the query service?]
**Indexer Version:** [What is the version of the indexer service?]
**Network Details:**
  * [Network]
  * [Block height, a block height where the issue is happening]
  * [Dictionary endpoint, if used]
