### ISSUE TITLE
Simplify multichain running

### ISSUE THREAD

**Issue by stwiname** [subquery/subql#1636]
### Description

Currently running a multichain project involves managing each chain instance separately, having a manifest file for each chain. There is lots of room for improvement to simplify this process

### Goals

To make it easier to run multichain projects (multiple nodes) both locally and on the managed service.
- Developers can codegen their project by running a single `yarn codegen` command that defaults to the Parent manifest
- Developers can build all child chain projects by running a single `yarn build` command that defaults to the Parent manifest
- Developers can build a single child chain by specifying the individual manifest on build
- Make generating the Docker Compose easy, one idea is a cli command to create a new chain manifest, add it to the Parent Manifest, and add it to the Docker Compose??

Then work with hosted service to
- Developers can publish a SubQuery multichain project (including all child chains) using the subql publish command (assuming their parent manifest is setup correctly

### Parent Manifest

A parent manifest seems like the obvious solution. This will include references to each chains specific project manifest as well as query service options that will override what is specified in each chain specific project.

Example:
```yaml
# subquery-multichain.yaml
specVersion: 1.0.0

projects:
   - ./path/to/chain1-project.yaml
   - ./path/to/chain2-project.yaml
   - ...

query:
  name: "@subql/query"
  version: "*"


```

### Stages

1. Define in code the manifest spec as we have with  current manifests.
2. CLI to publish and create multichain files. 
3. Further tooling
    * Validate schema matches for all projects
    * Run the multichain project locally
