### ISSUE TITLE
Windows Btree_gist not loading

### ISSUE THREAD

**Issue by youssefea** [subquery/subql#1865]
I had this issue multiple times running on Windows.
It seems that the script on load-extensions.sh does not run properly on Windows.

`kilt-spiritnet-credentials-example-subquery-node-1   | 2023-07-04T11:12:09.201Z <subql-node> INFO Current @subql/node version is 2.9.0
kilt-spiritnet-credentials-example-subquery-node-1   | 2023-07-04T11:12:09.452Z <db> WARN Database does not support SSL connection, will try to connect without it
kilt-spiritnet-credentials-example-subquery-node-1   | 2023-07-04T11:12:12.661Z <indexer> INFO indexer manager start
kilt-spiritnet-credentials-example-subquery-node-1   | 2023-07-04T11:12:12.682Z <api> INFO Using provided chain types
kilt-spiritnet-credentials-example-subquery-node-1   | 2023-07-04T11:12:13.412Z <store> INFO Historical state is enabled 
kilt-spiritnet-credentials-example-subquery-node-1   | 2023-07-04T11:12:13.418Z <store> ERROR Having a problem when syncing schema Error: Btree_gist extension is required to enable historical data, contact DB admin for support`

I had to run a seperate command to install Btree_gist

**Comment by stwiname** [comment]
Are you running with docker? How can we reproduce this?

**Comment by doutv** [comment]
Same issue when running docker-compose on WSL2:
```
stable-asset-subql-subquery-node-1   | 2023-12-06T09:57:29.791Z <StoreService> INFO Historical state is enabled 
stable-asset-subql-subquery-node-1   | 2023-12-06T09:57:29.795Z <dynamic-ds> INFO Loaded 0 dynamic datasources 
stable-asset-subql-subquery-node-1   | 2023-12-06T09:57:29.798Z <api> WARN skipTransactions is disabled, the project contains only event handlers, it could be enabled to improve indexing performance. 
stable-asset-subql-subquery-node-1   | 2023-12-06T09:57:29.805Z <StoreService> ERROR Having a problem when syncing schema Error: Btree_gist extension is required to enable historical data, contact DB admin for support
stable-asset-subql-subquery-node-1 exited with code 1
```

docker-compose.yml:
```yaml
version: '3'

services:
  postgres:
    image: postgres:12-alpine
    ports:
      - 5432:5432
    volumes:
      - .data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres

  subquery-node:
    image: onfinality/subql-node:latest
    depends_on:
      - "postgres"
    restart: always
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_DATABASE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
    volumes:
      - ./:/app
    command:
      - -f=/app
      - --db-schema=app

  graphql-engine:
    image: onfinality/subql-query:latest
    ports:
      - 3000:3000
    depends_on:
      - "postgres"
      - "subquery-node"
    restart: always
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_DATABASE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
    command:
      - --name=app
      - --playground
      - --indexer=http://subquery-node:3000
```
