### ISSUE TITLE
Support network filter for datasource

### ISSUE THREAD

**Issue by ianhe8x** [subquery/subql#188]
## Background
It is very common that user will create a subquery and expect to (re)use it for their testnet and mainnet. (e.g polkadot and kusama).

Network endpoint will be different for different networks, and since we already supported `--network-endpoint` flag to override it, this won't be an issue.

The other problem is startBlock, i suppose in some cases user will want it different.

After some discussion, our solution to this is let user define datasource for each of network they need to support, with a network filter. For the `mapping` part, we can make use of yaml's anchor to avoid redundancy.
Something like
```
definitions:
  - mapping: &mymapping
       handlers:
         - handler: handleBlock
           kind: substrate/BlockHandler

dataSources:
  - name: runtime
    kind: substrate/Runtime
    filter: 
        specName: polkadot
    startBlock: 1000
    mapping: *mymapping
  - name: runtime
    kind: substrate/Runtime
    filter: 
        specName: kusama
    startBlock: 2000
    mapping: *mymapping
```
