### ISSUE TITLE
subql-ethereum contract address not used in dict query

### ISSUE THREAD

**Issue by ianhe8x** [subquery/subql#1961]
### Prerequisites

* [ ] Are you running the latest version(s)?
* [ ] Have you searched the [documentation for your issue](https://academy.subquery.network/)?
* [ ] Did you search for an existing issue or pull request?

### Description
Here is a sample dictionary query for
```
  - kind: ethereum/Runtime
    startBlock: 41192135
    options:
      abi: sqt
      address: "0xcEE50Ee839a2ab3914cF4c3cbAc78f6F11E0c937"
    assets:
      sqt:
        file: "./abi/SQToken.json"
    mapping:
      file: "./dist/index.js"
      handlers:
        - handler: handleTransfer
          kind: ethereum/TransactionHandler
          filter:
            function: approve(address spender, uint256 rawAmount)
```
query is 
```
query ($evmTransactions_0_0: String!) {
  _metadata {
    lastProcessedHeight
    genesisHash
  }
  evmTransactions(
    filter: {
      or: [{ func: { equalTo: $evmTransactions_0_0 } }]
      blockHeight: { greaterThanOrEqualTo: "42792213", lessThan: "42802213" }
    }
    orderBy: BLOCK_HEIGHT_ASC
    first: 10
    distinct: [BLOCK_HEIGHT]
  ) {
    nodes {
      blockHeight
    }
  }
}
```

### Details

Contract Address need to be added into the query

**Local Environment:** [You can get this information from executing `subql version`.]
**Query Version:** [What is the version of the query service?]
**Indexer Version:** [What is the version of the indexer service?]
**Network Details:**
  * [Network]
  * [Block height, a block height where the issue is happening]
  * [Dictionary endpoint, if used]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Example project:** [A link to a minimal example that can reproduce the issue]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Any other information

Is there any other information you would like to add?
