### ISSUE TITLE
`unsafe` project args in runner not working

### ISSUE THREAD

**Issue by bz888** [subquery/subql#2017]
### Prerequisites

* [x] Are you running the latest version(s)?
* [x] Have you searched the [documentation for your issue](https://academy.subquery.network/)?
* [x] Did you search for an existing issue or pull request?

### Details

```
runner:
  node:
    name: "@subql/node"
    version: "*"
    options:
      unsafe: true
```

Unsafe should be enabled, but it is not.

### Any other information

Is there any other information you would like to add?
