### ISSUE TITLE
Ethereum Node Skips Blocks when Multiple Data Sources with different startBlock are added to project.yaml

### ISSUE THREAD

**Issue by filo87** [subquery/subql#2335]
### Prerequisites

* [X] Are you running the latest version(s)?
* [X] Have you searched the [documentation for your issue](https://academy.subquery.network/)?
* [X] Did you search for an existing issue or pull request?

### Description

subql-node-eth skips  blocks when multiple data sources with different startBlock are specified in a single project.yaml file. While each data source functions correctly when processed or included individually in a project.yaml, combining them leads to the following behavior:

1. Indexing starts and processes blocks successfully for the first data source until the startBlock of the second dataSource.
2. When the second data source with a higher startBlock is encountered, indexing directly jumps to a fully synced state, skipping all remaining blocks for both sources.

### Details

These details can help to reproduce the environment the issue is occurring

**Indexer Version:** 3.11.0
**Network Details:**
  * Centrifuge Mainnet
  * Issue appering on block 18721030 (same as StartBlock of `dataSource[1]`)

### Steps to Reproduce

1. Create a project.yaml file containing two data sources with different startBlock values.
2. Deploy the project and observe the indexing behavior.

**Example project:** https://github.com/embrio-tech/centrifuge-subql

**Expected behavior:** 
SubQuery should process each data source independently, ensuring all blocks are indexed regardless of individual startBlock values.

**Actual behavior:** 
Once arrived at indexing highest startBlock listed among the defined `dataSources`, the indexer skips all remaining blocks and events, jumping to a fully synced state.

### Any other information

```yaml
specVersion: 1.0.0
name: centrifuge-pools
version: 1.0.0
runner:
  node:
    name: '@subql/node-ethereum'
    version: '3'
  query:
    name: '@subql/query'
    version: '2'
description: >-
  SubQuery API powered by EMBRIO.tech to query Centrifuge chain data for
  analytics insights on how Centrifuge is unlocking economic opportunity for all
  by connecting people to borrow and lend money transparently and
  cost-effectively.
repository: https://github.com/centrifuge/pools-subql
schema:
  file: ./schema.graphql
network:
  chainId: '1'
  endpoint: "XXXX"
  dictionary: https://gx.api.subquery.network/sq/subquery/eth-dictionary
dataSources:
  - kind: ethereum/Runtime
    startBlock: 11063000
    options:
      abi: navFeed
    assets:
      navFeed:
        file: ./abi/navfeed.abi.json
      reserve:
        file: ./abi/reserve.abi.json
      shelf:
        file: ./abi/shelf.abi.json
      pile:
        file: ./abi/pile.abi.json
      multicall:
        file: ./abi/multicall.abi.json
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleEthBlock
          kind: ethereum/BlockHandler
          filter:
            modulo: 300
  - kind: ethereum/Runtime
    startBlock: 18721030
    options:
      abi: poolManager
    assets:
      poolManager:
        file: ./abi/poolManager.abi.json
      investmentManager:
        file: ./abi/investmentManager.abi.json
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleEvmDeployTranche
          kind: ethereum/LogHandler
          filter:
            topics:
              - >-
                DeployTranche(uint64 indexed poolId, bytes16 indexed trancheId,
                address indexed token)
templates:
  - name: TrancheTracker
    kind: ethereum/Runtime
    options:
      abi: erc20
    assets:
      erc20:
        file: ./abi/erc20.abi.json
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleEvmTransfer
          kind: ethereum/LogHandler
          filter:
            topics:
              - >-
                Transfer(address indexed from, address indexed to, uint256
                value)

```
![image](https://github.com/subquery/subql/assets/11260745/9baac40b-3950-4d40-a188-ecaf034f3f7e)
