### ISSUE TITLE
Failure when trying to decode a block for celestia mainnet

### ISSUE THREAD

**Issue by faust403** [subquery/subql#2670]
I wrote a subquery indexer for celestia according to [this](https://github.com/subquery/cosmos-subql-starter/tree/main/Celestia/celestia-starter). However, I get an error for every block this indexer tries to decode

`docker-compose.yml`:
```yml
subquery-node-celestia:
    image: subquerynetwork/subql-node-cosmos:latest
    depends_on:
      "postgres":
        condition: service_healthy
    restart: always
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_DATABASE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
    volumes:
      - ./:/app
    command:
      - ${SUB_COMMAND:-} # set SUB_COMMAND env variable to "test" to run tests
      - -f=/app/project-celestia-exec.yaml
      - --multi-chain
      - --db-schema=multi-transfers
      - --disable-historical
      - --batch-size=30
    healthcheck:
      test: ["CMD", "curl", "-f", "http://subquery-node-celestia:3000/ready"]
      interval: 3s
      timeout: 5s
      retries: 10
```

`project-celestia-exec.yaml`:
```yml
specVersion: 1.0.0
version: 0.0.1
name: drop-celestia-subquery
description: Drop celestia IBC subquery
runner:
  node:
    name: "@subql/node-cosmos"
    version: ">=3.0.0"
  query:
    name: "@subql/query"
    version: "*"
schema:
  file: ./schema.graphql
network:
  chainId: celestia
  endpoint:
    - https://public-celestia-rpc.numia.xyz
dataSources:
  - kind: cosmos/Runtime
    startBlock: 3928000
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleIbcRecvPacket
          kind: cosmos/MessageHandler
          filter:
            type: /ibc.core.channel.v1.MsgRecvPacket
            includeFailedTx: true
```

![Image](https://github.com/user-attachments/assets/ffef0cd1-53a4-403c-b984-4b08ee7aee73)
