### ISSUE TITLE
how to config two network in project.yaml,but i can see one  network:endpoint only

### ISSUE THREAD

**Issue by baidang201** [subquery/subql#331]
in https://doc.subquery.network/create/manifest.html#network-filters, 
i read that can be support both testnet and mainnet, but i see one  network:endpoint config in project.yaml
can you give me a  example?
how to add two network and match the specName to network endpoint?

```
network:
  endpoint: "wss://polkadot.api.onfinality.io/public-ws"

#Create a template to avoid redundancy
definitions:
  mapping: &mymapping
    handlers:
      - handler: handleBlock
        kind: substrate/BlockHandler

dataSources:
  - name: polkadotRuntime
    kind: substrate/Runtime
    filter:  #Optional
        specName: polkadot
    startBlock: 1000
    mapping: *mymapping #use template here
  - name: kusamaRuntime
    kind: substrate/Runtime
    filter: 
        specName: kusama
    startBlock: 12000 
    mapping: *mymapping # can reuse or change
```
