### ISSUE TITLE
EVM and other smart contract support

### ISSUE THREAD

**Issue by ianhe8x** [subquery/subql#444]
There're a few implementation of smart contract in the polkadot ecosystem, even for evm the interface to talk to evm are different among chains.
This ticket describes a high level picture what are needed for subql to support them.

## Principles
1. we use polkadot-js to interact with smart contracts, even the target chain provides an ethereum compatible rpc, they still support polkadot's standard rpc.
2. The code of plugin lives in subquery project, and is executed in the sandbox in subql-node. It means
  1. user decide the version of plugin to use or just provide one written by themselves.
  2. No dependencies added to subql-node

### 1. Filters provided in the query project scope.
```
dataSources:
  - name: contract
     kind: xxx
     processor: 
       file: 'path/to/code'
     filter:
       address: 
     assets:
      abi:
        file: path/to/abi.json
     mapping:
       handlers:
         - handler: handleTransfer
            kind: <Custom e.g: evm/transaction>
            filter:
              method: transfer(string,uint256)
         - handler: handleTransferEvent
            kind: <Custom e.g: evm/event>
            filter:
              method: TransferToken(string,uint256)
```

### 2. Predefined filters for popular smart contract chains, e.g: acala, moonbeam
```
  - name: contract
     kind: substrate/Ink!
     processor: 
       file: 'node_modules/@subql/contract-processor/dist/ink.js'
     filter:
       address: 
     assets:
      abi:
        file: path/to/abi.json
     mapping:
      handlers:
        - handler: handleInkCall
          kind: substrate/InkCall
          filter:
            message: filper()
            selector: 0x00aaFF
        - handler: handleInkEvent
          kind: substrate/InkEvent
          filter:
            event: Transfer
  - name: evmcontract
     kind: substrate/Acala-EVM
     processor: 
       file: 'node_modules/@subql/contract-processor/dist/acala-evm.js'
     filter:
       address: 
     assets:
      abi:
        file: path/to/abi.json
     mapping:
      handlers:
        - handler: handleEvmCall
          kind: substrate/AcalaEvmCall
          filter:
            method: transfer(string,uint256)
         - handler: handleTransferEvent
            kind: substrate/AcalaEvmEvent
            filter:
              event: TransferToken(string,uint256)
```

Interface to implement
Check PR for latest design
```
export interface SubqlCustomDatasource<
  K extends string = string,
  T extends SubqlNetworkFilter = SubqlNetworkFilter,
  M extends SubqlMapping = SubqlMapping<SubqlCustomHandler>
> extends ISubqlDatasource<M, T> {
  kind: K;
  assets: {[key: string]: CustomDataSourceAsset};
  processor: FileReference;
}

export interface HandlerInputTransformer<T extends SubqlHandlerKind, U> {
  (original: RuntimeHandlerInputMap[T], ds: SubqlCustomDatasource): U; //  | SubqlBuiltinDataSource
}

export interface SubqlDatasourceProcessor<K extends string, F extends SubqlNetworkFilter> {
  kind: K;
  validate(ds: SubqlCustomDatasource<K, F>): void;
  dsFilterProcessor(ds: SubqlCustomDatasource<K, F>, api: ApiPromise): boolean;
  handlerProcessors: {[kind: string]: SecondLayerHandlerProcessor<SubqlHandlerKind, unknown, unknown>};
}

export interface SecondLayerHandlerProcessor<K extends SubqlHandlerKind, F, E> {
  baseHandlerKind: K;
  baseFilter: RuntimeFilterMap[K] | RuntimeFilterMap[K][];
  transformer: HandlerInputTransformer<K, E>;
  filterProcessor: (filter: F, input: E, ds: SubqlCustomDatasource<string, SubqlNetworkFilter>) => boolean;
}
```

### 3. Dynamic datasources
