### ISSUE TITLE
Refactor project manifest file

### ISSUE THREAD

**Issue by ianhe8x** [subquery/subql#463]
<del> From the view of subquery developer, even though they need an archive node when developing the project, the endpoint is not necessary bond to this subquery project. That means if he decides to use managed indexing service from 3rd party, he is not responsible to provide the chain node endpoint.</del>

Goals:
1. Separate endpoint, dictionary into runtimeConfig.yaml (and passed from cli only, with default search place)
2. Separate type definition into its own file
3. Explicitly specify target network in the manifest file
  1. use genesisHash to identify network
  2. chainName for known chains
  3. deprecate support of specName filter
4. Allow project.yaml use other file name, if a subquery project supports both polkadot and kusama, they can create project-polkadot.yaml and project-kusama.yaml.
5. Define entry of mapping function in project.yaml, decouple it from package.json

Suggest
```
# project.yaml
specVersion: "0.2.0"
description: ""
repository: "https://github.com/subquery/subql-starter"

schema:
  file: ./schema.graphql

network:
  genesisHash: '0x'
  chaintypes:
    file: ./types.json

dataSources:
  - name: main
    kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
        - handler: handleEvent
          kind: substrate/EventHandler
          filter: #Filter is optional
            module: balances
            method: Deposit
        - handler: handleCall
          kind: substrate/CallHandler
```
