### ISSUE TITLE
Moonbeam evm processor

### ISSUE THREAD

**Issue by ianhe8x** [subquery/subql#550]
Follow-up to #444 
With the help of this processor, user can index calls and events to a specified contract address in the way

## Features:
- [x] filter by contract address
- [x] support event handler, filter by event name and topic
- [x] support call handler, filter by call name (? and parameter)
- [x] support make contract call within mapping
  - [x] the main contract
  - [x] other contract via address and abi
  - [x] code generation might be needed

## Usage
let's look at thegraph's spec
```
- kind: ethereum/contract
    name: NonfungiblePositionManager
    network: mainnet // lives in the ds filter in our spec
    source:
      address: '0xC36442b4a4522E871399CD717aBDD847Ab11FE88' // lives in the ds filter in our spec
      abi: NonfungiblePositionManager // we will also need a way to map contract to its abi
      startBlock: 12369651
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.4
      language: wasm/assemblyscript
      file: ./src/mappings/position-manager.ts
      entities: // not necessary linking entity to a datasource
        - Pool
        - Token
      abis: // for type generation and allow user do `let poolContract = PoolABI.bind(event.address)`
        - name: NonfungiblePositionManager
          file: ./abis/NonfungiblePositionManager.json
        - name: Pool
          file: ./abis/pool.json
        - name: Factory
          file: ./abis/factory.json
        - name: ERC20
          file: ./abis/ERC20.json
      eventHandlers:
        - event: IncreaseLiquidity(indexed uint256,uint128,uint256,uint256)
          handler: handleIncreaseLiquidity
        - event: DecreaseLiquidity(indexed uint256,uint128,uint256,uint256)
          handler: handleDecreaseLiquidity
        - event: Collect(indexed uint256,address,uint256,uint256)
          handler: handleCollect
        - event: Transfer(indexed address,indexed address,indexed uint256)
          handler: handleTransfer
```

What we can do here:
```
- kind: substrate/Moonbeam-EVM
    processor:
      file: node_modules/@subql/contract-processor/dist/moonbeam.js
    filter:
      address: <contract address>
    abi: SQT
    assets: // second thoughts maybe we don't need a generic struct for assets
      - abis:
           file: path/to/abi.json
   // or
    abis:
      - name: SQT
         file: path/to/abi.json
    mapping:
      handlers:
        - handler: handleEvmCall
          kind: substrate/AcalaEvmCall
          filter:
            method: transfer(string,uint256)
        - handler: handleTransferEvent
          kind: substrate/AcalaEvmEvent
          filter:
            event: TransferToken(string,uint256)
            topic: // optional
```

## Decode contract data/log
use ethers.js
