### ISSUE TITLE
Multiple (event) filters?

### ISSUE THREAD

**Issue by lamafab** [subquery/subql#813]
Hi, is it somehow possible to add multiple (event) filters to the Manifest File?

**Comment by lamafab** [comment]
Something like this would be nice:

```yaml
filter:
  - module: democrazy
    method: Proposed
    success: true
  - module: democrazy
    method: Tabled
    success: true
```

**Comment by stwiname** [comment]
You can do multiple handlers:

```yaml

- handler: handleProposal
  kind: subquery/EventHandler
  filter:
    - module: democrazy
      method: Proposed
      success: true
- handler: handleTabled
  kind: subquery/EventHandler
  filter:
    - module: democrazy
      method: Tabled
      success: true
```

The handler function can be the same if you wish.
